import { addDays } from "../lib/helperFuncs.js";

const archive = [
  {
    nextContactDate: addDays(3),
    leadSource: "Google Ads",
    student: {
      firstName: "Noah",
      lastName: "Morrison",
      instrument: "Bass Guitar",
      groupClass: "Beginner Band",
      age: 15,
    },
    guardian: {
      firstName: "Liam",
      lastName: "Morrison",
    },
    contact: { phone: "0423456789", email: "liam@email.com" },
    followUp: [],
    trialLesson: {
      date: "",
      time: { hour: "", min: "", twelveHr: "" },
      location: "",
      instrument: "",
      teacher: "",
      followUp: [],
    },
  },
  {
    nextContactDate: addDays(1),
    leadSource: "Referral",
    student: {
      firstName: "Emma",
      lastName: "Clark",
      instrument: "Violin",
      groupClass: "",
      age: 12,
    },
    guardian: {
      firstName: "Anna",
      lastName: "Clark",
    },
    contact: { phone: "0438765432", email: "anna@email.com" },
    followUp: [],
    trialLesson: {
      date: addDays(2),
      time: { hour: "5", min: "00", twelveHr: "pm" },
      location: "Music Hall",
      instrument: "Violin",
      teacher: "Niccolò Paganini",
      followUp: [],
    },
  },
  {
    nextContactDate: addDays(5),
    leadSource: "Flyer",
    student: {
      firstName: "Olivia",
      lastName: "Taylor",
      instrument: "Flute",
      groupClass: "Advanced Winds",
      age: 18,
    },
    guardian: {
      firstName: "",
      lastName: "",
    },
    contact: { phone: "0456123987", email: "olivia@email.com" },
    followUp: [
      { admin: "EF", method: { email: true }, notes: "Emailed details about class schedule." },
    ],
    trialLesson: {
      date: addDays(7),
      time: { hour: "4", min: "15", twelveHr: "pm" },
      location: "Studio C",
      instrument: "Flute",
      teacher: "Jean-Pierre Rampal",
      followUp: [],
    },
  },
  {
    nextContactDate: addDays(4),
    leadSource: "Facebook",
    student: {
      firstName: "William",
      lastName: "Evans",
      instrument: "Saxophone",
      groupClass: "",
      age: 21,
    },
    guardian: {
      firstName: "",
      lastName: "",
    },
    contact: { phone: "0467891234", email: "william@email.com" },
    followUp: [],
    trialLesson: {
      date: addDays(6),
      time: { hour: "6", min: "30", twelveHr: "pm" },
      location: "Jazz Room",
      instrument: "Saxophone",
      teacher: "Charlie Parker",
      followUp: [],
    },
  },
  {
    nextContactDate: addDays(2),
    leadSource: "Instagram",
    student: {
      firstName: "Sophia",
      lastName: "Lee",
      instrument: "Drums",
      groupClass: "Percussion Ensemble",
      age: 13,
    },
    guardian: {
      firstName: "Megan",
      lastName: "Lee",
    },
    contact: { phone: "0412987654", email: "megan@email.com" },
    followUp: [],
    trialLesson: {
      date: addDays(3),
      time: { hour: "2", min: "45", twelveHr: "pm" },
      location: "Studio D",
      instrument: "Drums",
      teacher: "Buddy Rich",
      followUp: [],
    },
  },
  {
    nextContactDate: addDays(7),
    leadSource: "Google Ads",
    student: {
      firstName: "James",
      lastName: "Wright",
      instrument: "Piano",
      groupClass: "Jazz Improvisation",
      age: 19,
    },
    guardian: {
      firstName: "",
      lastName: "",
    },
    contact: { phone: "0491234567", email: "james@email.com" },
    followUp: [
      {
        admin: "GH",
        method: { voicemail: true, email: true },
        notes: "Left voicemail and emailed syllabus.",
      },
    ],
    trialLesson: {
      date: addDays(9),
      time: { hour: "3", min: "00", twelveHr: "pm" },
      location: "Room 2",
      instrument: "Piano",
      teacher: "Oscar Peterson",
      followUp: [],
    },
  },
  {
    nextContactDate: addDays(3),
    leadSource: "Walk-in",
    student: {
      firstName: "Isabella",
      lastName: "Martinez",
      instrument: "Clarinet",
      groupClass: "",
      age: 16,
    },
    guardian: {
      firstName: "Carlos",
      lastName: "Martinez",
    },
    contact: { phone: "0487654321", email: "carlos@email.com" },
    followUp: [],
    trialLesson: {
      date: "",
      time: { hour: "", min: "", twelveHr: "" },
      location: "",
      instrument: "",
      teacher: "",
      followUp: [],
    },
  },
  {
    nextContactDate: addDays(2),
    leadSource: "Email",
    student: {
      firstName: "Liam",
      lastName: "Hernandez",
      instrument: "Trumpet",
      groupClass: "Beginner Brass",
      age: 14,
    },
    guardian: {
      firstName: "Julia",
      lastName: "Hernandez",
    },
    contact: { phone: "0432104321", email: "julia@email.com" },
    followUp: [],
    trialLesson: {
      date: addDays(4),
      time: { hour: "4", min: "00", twelveHr: "pm" },
      location: "Room 6",
      instrument: "Trumpet",
      teacher: "Wynton Marsalis",
      followUp: [],
    },
  },
  {
    nextContactDate: addDays(5),
    leadSource: "Flyer",
    student: {
      firstName: "Charlotte",
      lastName: "Davis",
      instrument: "Guitar",
      groupClass: "Rock Band",
      age: 17,
    },
    guardian: {
      firstName: "",
      lastName: "",
    },
    contact: { phone: "0476123984", email: "charlotte@email.com" },
    followUp: [],
    trialLesson: {
      date: addDays(8),
      time: { hour: "5", min: "30", twelveHr: "pm" },
      location: "Studio A",
      instrument: "Guitar",
      teacher: "Eric Clapton",
      followUp: [],
    },
  },
  {
    nextContactDate: addDays(6),
    leadSource: "Website",
    student: {
      firstName: "Benjamin",
      lastName: "Harris",
      instrument: "Cello",
      groupClass: "",
      age: 20,
    },
    guardian: {
      firstName: "",
      lastName: "",
    },
    contact: { phone: "0461123456", email: "benjamin@email.com" },
    followUp: [
      { admin: "IJ", method: { email: true }, notes: "Shared trial details via email." },
    ],
    trialLesson: {
      date: addDays(10),
      time: { hour: "6", min: "00", twelveHr: "pm" },
      location: "Practice Room 1",
      instrument: "Cello",
      teacher: "Yo-Yo Ma",
      followUp: [],
    },
  },
];


export default archive;
